[package]
name = "henri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = { version ="0.4", features = ["serde"] }
nom = "7.1.3"
